const data = require('./seedData.js');

const getRestaurants = () => {
  let results = [];

  for (var i = 0; i < 100; i++) {
    results.push(data.generateRestaurant());
  }

  console.log('Logging results => ', results);
};

getRestaurants();

// For each restaurant, generate 2 to 10 collections (max num that shows up on a page is 10)
// Random int between 1 and 3
// If 1, collection will be named after a city
// If 2, collection will be named after the type of food that the current restaurant has
// If 3, collection will be named after a randomly generated adjective from adjectives list

// Once every restaurant has a collection, need to add new restaurants to each collection
// Iterate over each collection, and generate 10 to 50 new restaurants
// Add each restaurant to the restaurants array
// Also, store each restaurant in a collection in that collection's 'restaurants' property --> this will come in handy when making queries to insert info into the db

// WHEN GENERATING RESTAURANTS FOR COLLECTIONS:
//  Take into account whether the collection has a city name or food type
//  If it does, all restaurants generated need to be in that city or of that food type

// Now we should have:
//  1. An array of restaurants (First 100 of which we'll build pages for)
//  2. An array of collections, which includes an array of restaurants in that collection as a property of the collection

// QUERY ORDER
//  1. Insert each restaurant into the restaurants table
//  2. Insert each collection into the collections table
//     When each collection has been inserted, results will return an obj with the insertion id
//     Iterate over restaurants in that collection's restaurants array
//     Find the id of each restaurant in the restaurants table, and add that restaurant id alongside the collection's id in the join table
/*
                restaurant_id  |  collections_id
                    1                   1
                    9                   1
                    15                  1
                    23                  1
                    1                   2
                    3                   2
                    16                  2
                    28                  2
*/


// Collections
//  Id
//  Name --> cities or food types
//  User (creator) --> add last names table
//  Followers --> Random number between 1 and 1000
//  User followers --> Random number between 1 and 1000
//  User ratings_num --> Random number between 1 and 1000
//  Latest update --> Random date in last 3 years
//  User image

// generate Collection
// generate random collection name
//    Random name will be generated by selecting a 1 or 2 randomly
//    If a 1, pick a random food type
// generate 10 to 30 random restaurants
// use randomNumber generator to generate number of restaurants between 10 and 30
// Iterate from 1 to (10 < x < 30) and

// Question: how do we make sure that every restaurant we generate in our restaurants table is included in a collection that we generate?


// GETTING COLLECTIONS FOR A GIVEN RESTAURANT
// When a restaurant page is loaded, should lookup id of that restaurant in restaurants table
// Then, should use that restaurant id to look up ids of all collections that include that restaurant in restaurants_collections join table